#pragma once

#include "sdkconfig.h"
#include "esp_heap_caps.h"

#if defined(CONFIG_SPIRAM) && CONFIG_SPIRAM
#define ESP_MINER_HEAP_ALLOC_CAPS (MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT)
#define ESP_MINER_TASK_STACK_CAPS (MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT | MALLOC_CAP_32BIT)
#define ESP_MINER_TASK_STACK_SIZE_DEFAULT (8192)
#define ESP_MINER_TASK_STACK_SIZE_SMALL (6144)
#define ESP_MINER_TASK_STACK_SIZE_TINY (4096)
#else
#define ESP_MINER_HEAP_ALLOC_CAPS (MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT)
#define ESP_MINER_TASK_STACK_CAPS (MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT | MALLOC_CAP_32BIT)
#define ESP_MINER_TASK_STACK_SIZE_DEFAULT (4096)
#define ESP_MINER_TASK_STACK_SIZE_SMALL (3072)
#define ESP_MINER_TASK_STACK_SIZE_TINY (2048)
#endif
